project:
  type: website
  output-dir: docs
website:
  title: "ğŸ¡ - Glossar"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/soekni
      - icon: mastodon
        href: https://dresden.network/@7eruS
format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual

